#!/usr/bin/env python
"""
Generate a sample Content Correctness Audit Recommendations report

This serves as a template for the Codex agent to understand the expected output format.
"""

from datetime import datetime
from pathlib import Path


def generate_sample_report(output_path: Path) -> None:
    """Generate a sample recommendations report"""

    report_content = f"""# Content Correctness Audit Recommendations

**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Mode:** sample
**Commit:** (sample)

---

## Summary

- Analyzed documents: 19 (12 plans, 3 governance, 4 design)
- Rules/Design findings: 3
- Plan status findings: 4
- Actionable recommendations: 7

---

## Findings

### Rules & Design Class

#### [R1] Release Gate Manual Checks Incomplete
- **File:** `docs/governance/release-gate.md`
- **Finding:** M7 check ("Verify Mini Program screenshots") documented but last evidence is from 2026-03-15
- **Evidence:** Document references this check, but no recent PR/commit links suggest ongoing validation
- **Recommendation:** Either update with recent validation evidence or mark as "not yet enforced"
- **Impact:** High — release gate must be fully operational
- **Action Priority:** MUST FIX

#### [R2] Terminology: "Period" vs "Menstrual Cycle"
- **Files:** `docs/contracts/README.md`, `docs/plans/2026-03-29-mvp-definition-and-gap-list.md`
- **Finding:** Inconsistent use: "period" 12 times, "menstrual cycle" 7 times in adjacent sections
- **Evidence:** Same concept, different names within 30 lines of each other
- **Recommendation:** Standardize on one term (suggest "period" for brevity) across contracts and plans
- **Action Priority:** SHOULD FIX

#### [R3] Missing Error Handling Rules
- **File:** `docs/governance/release-gate.md`
- **Finding:** Release gate procedures exist, but no corresponding error handling or rollback documentation
- **Evidence:** Release gate defines success criteria but not failure recovery steps
- **Recommendation:** Create `docs/governance/error-handling-guide.md` (future-risk debt)
- **Action Priority:** SHOULD ADD

### Plan Status Class

#### [P1] 2026-03-30-batch-interaction-hardening-status.md
- **Status:** In Progress
- **Evidence:** Document has "Remaining Items (H1-H3 verified, H4 pending)" section
- **Completion Estimate:** 50% (H4 work not started)
- **Last Updated:** 2026-03-30 (current)
- **Recommendation:** Keep under active monitoring; expect status update within 2 weeks
- **Action:** None needed (on schedule)

#### [P2] 2026-03-29-mvp-definition-and-gap-list.md
- **Status:** Complete ✓
- **Evidence:** All gap categories show "✓ Done" or "Already Complete"
- **Completion:** 100%
- **Last Updated:** 2026-03-29 (1 day old, current)
- **Recommendation:** Archive to `docs/plans/completed/` per content-audit-policy
- **Action:** MOVE FILE

#### [P3] 2026-03-28-three-week-home-demo-implementation-plan.md
- **Status:** Complete ✓
- **Evidence:** All tasks (Task 1-10) have completion markers
- **Completion:** 100%
- **Last Updated:** 2026-03-28 (2 days old)
- **Recommendation:** Archive to `docs/plans/completed/`
- **Action:** MOVE FILE

#### [P4] 2026-03-27-backend-implementation-plan.md
- **Status:** Stale
- **Evidence:** Document date is 2026-03-27 (3 days old); code has 8 commits since then
- **Concern:** Document status may not reflect current code state
- **Recommendation:** Refresh status or confirm still accurate
- **Action:** HUMAN REVIEW

---

## Recommended Actions (Priority Order)

| Priority | Action | Effort | Owner |
|----------|--------|--------|-------|
| MUST | Fix Release Gate M7 evidence | 15 min | Maintainer |
| SHOULD | Standardize "period" terminology | 20 min | Tech Writer |
| SHOULD | Add error handling guide | 45 min | Architect |
| SHOULD | Archive 2 completed plans | 5 min | Maintainer |
| REVIEW | Refresh batch-hardening status | 10 min | Impl Team |

---

## Next Human Steps

1. **Review** this report for accuracy (Est. 5-10 min)
2. **Assess** which recommendations to implement
3. **Approve** changes (document decision)
4. **Execute** manually:
   - Edit files (terminology, rules)
   - Move files (archive completed plans)
   - Update status docs (refresh stale content)

---

## Sample Metadata Used

This report was generated from:
- **Plans analyzed:** 12 documents, 19 status markers found, 4 with "remaining" sections
- **Governance rules:** 3 files, 12 rule definitions extracted, 8 command references
- **Design docs:** 4 files, 18 design decisions traced
- **Document Audit data:** 40 findings (mostly orphan/misplaced, no stale command issues)

---

## Notes

- This is a **sample report** showing the expected format and content structure
- Actual recommendations will be generated by Codex agent using document content analysis
- No changes should be made based on this sample — wait for real audit results
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_content, encoding="utf-8")
    print(f"Sample report written to {output_path}")


if __name__ == "__main__":
    output_path = Path("docs/generated/content-audit/latest-recommendations.md")
    generate_sample_report(output_path)
